/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_codeandme_jni_JNITest */

#ifndef _Included_com_codeandme_jni_JNITest
#define _Included_com_codeandme_jni_JNITest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_codeandme_jni_JNITest
 * Method:    hello
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_codeandme_jni_JNITest_hello
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
